# These are supported funding model platforms

github: [ericrallen]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: ericrallen
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://supporters.eff.org/donate/
